site_name: EmuDeck Wiki
site_url: https://emudeck.github.io
repo_url: https://github.com/EmuDeck/emudeck.github.io
repo_name: emudeck.github.io
copyright: > 
    Copyright Creative Commons Attribution-ShareAlike 4.0 International
#    <a href="#__consent">Change cookie settings</a>
nav:
    - Home: 'index.md'
    - About: 'about.md'
    - EmuDeck Website: 'https://www.emudeck.com/'
    - EmuDeck GitHub: 'https://github.com/dragoonDorise/EmuDeck'
    - EmuDeck Wiki GitHub: 'https://github.com/EmuDeck/emudeck.github.io'
    - EmuDeck Discord: 'https://discord.gg/b9F7GpXtFP'
    - EmuDeck Blog: 'blog/index.md'   
    - BIOS and ROMs Cheat Sheet: 'cheat-sheet.md'
    - Community Games Compatibility Database: 'https://brantje.github.io/emudeck-compatibility-list/'
    - Donations: 'donations.md'
    - How to Install EmuDeck:
        - 'EmuDeck for SteamOS': 
            - 'how-to-install-emudeck/steamos/index.md'
        - 'EmuDeck for Windows': 
            - 'how-to-install-emudeck/windows/index.md'
        - 'EmuDeck for Linux': 
            - 'how-to-install-emudeck/linux/index.md'
    - Frequently Asked Questions:
        - 'EmuDeck for SteamOS': 
            - 'frequently-asked-questions/steamos/index.md' 
        - 'EmuDeck for Windows': 
            - 'frequently-asked-questions/windows/index.md' 
        - 'EmuDeck for Linux': 
            - 'frequently-asked-questions/linux/index.md' 
    - Known Issues:
        - 'EmuDeck for SteamOS': 
            - 'known-issues/steamos/index.md'
        - 'EmuDeck for Windows': 
            - 'known-issues/windows/index.md'
        - 'EmuDeck for Linux': 
            - 'known-issues/linux/index.md'
    - Troubleshooting:
        - 'EmuDeck for SteamOS': 
            - 'troubleshooting/steamos/index.md'
        - 'EmuDeck for Windows': https://github.com/dragoonDorise/EmuDeck/pull/1002
            - 'troubleshooting/windows/index.md'
        - 'EmuDeck for Linux': 
            - 'troubleshooting/linux/index.md'
    - EmuDeck Maintenance:
        - 'Updating on SteamOS': 'emudeck-maintenance/steamos/updating.md'
        - 'Updating on Windows': 'emudeck-maintenance/windows/updating.md'
    - Controls and Hotkeys:
        - EmuDeck for SteamOS:
            - 'Controls 101': 'controls-and-hotkeys/steamos/controls-101.md' 
            - 'Hotkeys': 'controls-and-hotkeys/steamos/hotkeys.md'
            - 'External Controllers': 'controls-and-hotkeys/steamos/external-controllers.md'
        - EmuDeck for Windows:  
            - 'Controls 101': 'controls-and-hotkeys/windows/controls-101.md'
            - 'Hotkeys': 'controls-and-hotkeys/windows/hotkeys.md'
    - EmuDeck Application:
        - 'EmuDeck for SteamOS': 
            - 'EmuDeck Application 101': 'emudeck-application/steamos/emudeck-application-101.md'
            - 'EmuDeck Store': 'emudeck-application/steamos/emudeck-store.md'
        - 'EmuDeck for Windows': 
            - 'EmuDeck Application 101': 'emudeck-application/windows/emudeck-application-101.md'
    - Tools:
        - Cloud Services:
            - 'Cloud Services on SteamOS': 'tools/steamos/cloud-services.md'
        - ES-DE:
            - 'ES-DE on SteamOS': 'tools/steamos/es-de.md'
            - 'ES-DE on Windows': 'tools/windows/es-de.md'
        - Steam ROM Manager:
            - 'Steam ROM Manager on SteamOS': 'tools/steamos/steam-rom-manager.md'
            - 'Steam ROM Manager on Windows': 'tools/windows/steam-rom-manager.md'
        - Pegasus:
            - 'Pegasus on SteamOS': 'tools/steamos/pegasus.md'
            - 'Pegasus on Windows': 'tools/windows/pegasus.md'
    - Emulators:
        - Supported Emulators:
            - Supported Emulators on SteamOS: 'emulators/steamos/supported-emulators.md'
            - Supported Emulators on Windows: 'emulators/windows/supported-emulators.md'
        - BigPEmu (Atari Jaguar):
            - 'BigPEmu on SteamOS': 'emulators/steamos/bigpemu.md'
        - Cemu (Wii U): 
            - 'Cemu on SteamOS': 
                - 'emulators/steamos/cemu/index.md'
                - 'Cemu (Native) on SteamOS': 'emulators/steamos/cemu/cemu-native.md'
                - 'Cemu (Proton) on SteamOS': 'emulators/steamos/cemu/cemu-proton.md'
            - 'Cemu on Windows': 'emulators/windows/cemu.md'
        - Citra (Nintendo 3DS):
            - 'Citra on SteamOS': 'emulators/steamos/citra.md'
            - 'Citra on Windows': 'emulators/windows/citra.md'
        - Dolphin (GameCube and Wii):
            - 'Dolphin on SteamOS': 'emulators/steamos/dolphin.md'
            - 'Dolphin on Windows': 'emulators/windows/dolphin.md'
        - DuckStation (PlayStation 1):
            - 'DuckStation on SteamOS': 'emulators/steamos/duckstation.md'
            - 'DuckStation on Windows': 'emulators/windows/duckstation.md'
        - Flycast (Dreamcast):
            - 'Flycast on SteamOS': 'emulators/steamos/flycast.md'
        - MAME:
            - 'MAME on SteamOS': 'emulators/steamos/mame.md'
        - melonDS (Nintendo DS) (Standalone):
            - 'melonDS on SteamOS': 'emulators/steamos/melonds.md'
            - 'melonDS on Windows': 'emulators/windows/melonds.md'
        - mGBA (GB, GBC, and GBA) (Standalone):
            - 'mGBA on SteamOS': 'emulators/steamos/mgba.md'
        - Model 2 Emulator (Sega Model 2):
            - 'Model 2 Emulator on SteamOS': 'emulators/steamos/model-2-emulator.md'
        - PCSX2 (PlayStation 2):
            - 'PCSX2 on SteamOS': 'emulators/steamos/pcsx2.md'
            - 'PCSX2 on Windows': 'emulators/windows/pcsx2.md'
        - PPSSPP (PlayStation Portable) (Standalone):
            - 'PPSSPP on SteamOS': 'emulators/steamos/ppsspp.md'
            - 'PPSSPP on Windows': 'emulators/windows/ppsspp.md'
        - PrimeHack: 
            - 'PrimeHack on SteamOS': 'emulators/steamos/primehack.md'
        - RetroArch:
            - 'RetroArch on SteamOS': 'emulators/steamos/retroarch.md'
            - 'RetroArch on Windows': 'emulators/windows/retroarch.md'
        - Rosalie's Mupen GUI (Nintendo 64) (Standalone):
            - "Rosalie's Mupen GUI on SteamOS": 'emulators/steamos/rmg.md'
        - RPCS3 (PlayStation 3):
            - 'RPCS3 on SteamOS': 'emulators/steamos/rpcs3.md'
            - 'RPCS3 on Windows': 'emulators/windows/rpcs3.md'
        - Ryujinx (Nintendo Switch):
            - 'Ryujinx on SteamOS': 'emulators/steamos/ryujinx.md'
            - 'Ryujinx on Windows': 'emulators/windows/ryujinx.md'
        - ScummVM:
            - 'ScummVM on SteamOS': 'emulators/steamos/scummvm.md'
        - Supermodel (Sega Model 3):
            - 'Supermodel on SteamOS': 'emulators/steamos/supermodel.md'
        - Vita3K (PlayStation Vita):
            - 'Vita3K on SteamOS': 'emulators/steamos/vita3k.md'
        - Xemu (OG Xbox):
            - 'Xemu on SteamOS': 'emulators/steamos/xemu.md'
        - Xenia (Xbox 360):
            - 'Xenia on SteamOS': 'emulators/steamos/xenia.md'
        - Yuzu (Nintendo Switch):
            - 'Yuzu on SteamOS': 'emulators/steamos/yuzu.md'
            - 'Yuzu on Windows': 'emulators/windows/yuzu.md'
    - Save Management:
        - Save Management on SteamOS: 'save-management/steamos/save-management.md'
        - Save Management on Windows: 'save-management/windows/save-management.md'
    - File Management:
        - File Management on SteamOS: 'file-management/steamos/file-management.md'
        - File Management on Windows: 'file-management/windows/file-management.md'
    - Community Creations:
        - EmuDeck for SteamOS:
            - Community Creations: 'community-creations/steamos/community-creations.md'
            - Community Game Configurations: 'community-creations/steamos/community-game-configurations.md'
            - Third Party Emulation (Decompilations and Games): 'community-creations/steamos/third-party-emulation.md'  
            - Tools and Guides: 'community-creations/steamos/tools-and-guides.md'  
        - EmuDeck for Windows:
            - Community Creations: 'community-creations/windows/community-creations.md'
    - EmuDeck Plugins:
        - EmuDeck Plugins:
            - 'emudeck-plugins/index.md'
            - 'DeckyControls': 'emudeck-plugins/deckycontrols.md'
            - 'Emuchievements': 'emudeck-plugins/emuchievements.md'
            - 'MetaDeck': 'emudeck-plugins/metadeck.md'
    - Contributing to EmuDeck: 
        - How to Contribute: 'how-to-contribute.md'
theme:
    # Theme: https://squidfunk.github.io/mkdocs-material/
    name: material  
    custom_dir: overrides
    features:
    # QOL features
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs.sticky
    - navigation.path
    - toc.follow 
    - navigation.indexes 
    - content.tooltips
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - content.code.annotate
    - announce.dismiss
    logo: assets/logo.png
    favicon: images/favicon.png
    font:
        text: Open Sans
        code: IBM Plex Mono
    # Color scheme and toggle button for dark/light mode
    palette:
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: 'blue'
        accent: 'light blue'
        toggle:
            icon: material/brightness-4
            name: Toggle light mode
      - media: "(prefers-color-scheme: light)"
        scheme: light
        primary: 'blue'
        accent: 'light blue'
        toggle:
            icon: material/brightness-7
            name: Toggle dark mode
markdown_extensions:
    # permalink:true adds anchors to headers
    - toc:
        permalink: ''
    # pymdownx.superfences adds diagrams
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    # adds emojis and allows for custom emojis placed in overrides/.icons
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
        options:
            options:
            custom_icons: 
                - overrides/.icons
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.keys
    - def_list
    - sane_lists
    - attr_list
    - tables
    - abbr
    - pymdownx.snippets
    # Adds keyboard icons, may be able to add steam deck buttons
    - pymdownx.keys
    # Allows for writing markdown in HTML
    - md_in_html       
    # Adds checkboxes   
    - pymdownx.tasklist
    # Adds highlighting and subscript and superscript
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true        
        use_pygments: true
    - pymdownx.inlinehilite
    - admonition
    - footnotes
    - pymdownx.smartsymbols
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.magiclink
# plugins section, search is an included plugin but if adding any new plugins, needs to be stated here as well
plugins:
    - search:
        separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
    - glightbox
    # Getting the following error:
    # "Config value 'plugins': Plugin 'i18n' option 'languages': Expected type: <class 'dict'> but received: <class 'list'>"
    # Will investigate later, commenting out for now. 
    #- i18n:
       # docs_structure: suffix
        # languages:
        #  - locale: en
        #    default: true
        #    name: English
        #    build: true
        #   - locale: es
        #     name: Español
        #     build: true
        #   - locale: fr
        #     name: Français
        #     build: true
    - table-reader:
        base_path: "config_dir"
        data_path: "docs/tables/"
        search_page_directory: True
        allow_missing_files: True
    - blog
    - rss:
        enabled: !ENV [CI, false]
        match_path: blog/posts/.* 
        date_from_meta:
            as_creation: date
            datetime_format: "%Y-%m-%d %H:%M"
        categories:
            - categories
            - tags 
        image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
# Footer
extra:
  social:
    - icon: 'custom/logo'
      link: 'https://www.emudeck.com/'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/EmuDeck'
    - icon: 'fontawesome/brands/discord'
      link: 'https://discord.gg/b9F7GpXtFP'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/EmuDeck'
    - icon: 'fontawesome/brands/patreon'
      link: 'https://www.patreon.com/dragoonDorise'
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/custom.js
extra_css:
  - css/github-permalink-style.css
  - css/github-tables.css
  - css/custom.css
# Analytics - To Do
#  consent:
#    title: Cookie consent
#    description: >-
#        We use cookies to recognize your repeated visits and preferences, as well
#        as to measure the effectiveness of our documentation and whether users
#        find what they're searching for. With your consent, you're helping us to
#        make our documentation better.
#    actions:
#        - accept
#        - reject
#        - manage
