site_name: EmuDeck Wiki
site_url: https://emudeck.github.io
repo_url: https://github.com/EmuDeck/emudeck.github.io
repo_name: emudeck.github.io
copyright: Copyright Creative Commons Attribution-ShareAlike 4.0 International
nav:
    - EmuDeck Website: 'https://www.emudeck.com/'
    - Home: 'index.md'
    - About: 'about.md'
    - How to Install EmuDeck:
        - 'EmuDeck for SteamOS': 
            - 'How to Install EmuDeck for SteamOS': 'how-to-install-emudeck/steamos/emudeck-for-steamos.md'
        - 'EmuDeck for Windows': 
            - 'Prerequisites': 'how-to-install-emudeck/windows/prerequisites.md'
            - 'How to Install EmuDeck for Windows': 'how-to-install-emudeck/windows/emudeck-for-windows.md'
        - 'EmuDeck for Linux': 
            - 'Prerequisites': 'how-to-install-emudeck/linux/prerequisites.md'
            - 'How to Install EmuDeck for Linux': 'how-to-install-emudeck/linux/emudeck-for-linux.md'
    - Getting Started with EmuDeck:
        - 'EmuDeck for SteamOS': 
            - 'Frequently Asked Questions': 'getting-started-with-emudeck/steamos/frequently-asked-questions.md' 
            - 'Supported Emulators': 'getting-started-with-emudeck/steamos/supported-emulators.md' 
        - 'EmuDeck for Windows': 
            - 'Frequently Asked Questions': 'getting-started-with-emudeck/windows/frequently-asked-questions.md' 
            - 'Supported Emulators': 'getting-started-with-emudeck/windows/supported-emulators.md' 
    - Common Issues:
        - 'EmuDeck for SteamOS': 
            - 'Common Issues': 'common-issues/common-issues-emudeck-for-steamos.md'
        - 'EmuDeck for Windows': 
            - 'Common Issues': 'common-issues/common-issues-emudeck-for-windows.md'
    - EmuDeck Essentials:
        - 'Cheat Sheet': 'emudeck-essentials/cheat-sheet.md'
        - 'EmuDeck for SteamOS':
            - 'Updating': 'emudeck-essentials/steamos/updating.md'
            - 'Hotkeys': 'emudeck-essentials/steamos/hotkeys.md'
            - 'Controls 101': 'emudeck-essentials/steamos/controls-101.md'
            - 'EmuDeck Community Games Compatibility List': 'https://brantje.github.io/emudeck-compatibility-list/'
        - 'EmuDeck for Windows':
            - 'Updating': 'emudeck-essentials/windows/updating.md'
            - 'Hotkeys': 'emudeck-essentials/windows/hotkeys.md'
            - 'Controls 101': 'emudeck-essentials/windows/controls-101.md'
    - EmuDeck Application:
        - 'Cloud Saves': 'emudeck-application/cloud-saves.md'
        - 'EmuDeck for SteamOS': 
            - 'Cloud Services': 'emudeck-application/steamos/cloud-services.md'
            - 'EmuDeck Application 101': 'emudeck-application/steamos/emudeck-application-101.md'
            - 'EmuDeck Store': 'emudeck-application/steamos/emudeck-store.md'
        - 'EmuDeck for Windows': 
            - 'EmuDeck Application 101': 'emudeck-application/windows/emudeck-application-101.md'
    - Tools:
        - EmuDeck for SteamOS:
            - 'Steam ROM Manager': 'tools/steamos/steam-rom-manager.md'
            - 'EmulationStation-DE': 'tools/steamos/emulationstation-de.md'
        - EmuDeck for Windows:
            - 'Steam ROM Manager': 'tools/windows/steam-rom-manager.md'
            - 'EmulationStation-DE': 'tools/windows/emulationstation-de.md'
    - Emulators:
        - Cemu: 
            - 'Cemu SteamOS': 
                - 'Cemu SteamOS Landing Page': 'emulators/steamos/cemu.md'
                - 'Cemu (Native) SteamOS': 'emulators/steamos/cemu-native.md'
                - 'Cemu (Proton) SteamOS': 'emulators/steamos/cemu-proton.md'
            - 'Cemu Windows':
                - 'Cemu - Windows': 'emulators/windows/cemu.md'
        - Citra:
            - 'Citra SteamOS': 'emulators/steamos/citra.md'
            - 'Citra Windows': 'emulators/windows/citra.md'
        - Dolphin:
            - 'Dolphin SteamOS': 'emulators/steamos/dolphin.md'
            - 'Dolphin Windows': 'emulators/windows/dolphin.md'
        - DuckStation:
            - 'DuckStation SteamOS': 'emulators/steamos/duckstation.md'
            - 'DuckStation Windows': 'emulators/windows/duckstation.md'
        - MAME:
            - 'MAME SteamOS': 'emulators/steamos/mame.md'
        - melonDS:
            - 'melonDS SteamOS': 'emulators/steamos/melonds.md'
            - 'melonDS Windows': 'emulators/windows/melonds.md'
        - mGBA:
            - 'mGBA SteamOS': 'emulators/steamos/mgba.md'
        - PCSX2:
            - 'PCSX2 SteamOS': 'emulators/steamos/pcsx2.md'
            - 'PCSX2 Windows': 'emulators/windows/pcsx2.md'
        - PPSSPP:
            - 'PPSSPP SteamOS': 'emulators/steamos/ppsspp.md'
            - 'PPSSPP Windows': 'emulators/windows/ppsspp.md'
        - PrimeHack:
            - 'PrimeHack SteamOS': 'emulators/steamos/primehack.md'
        - RetroArch:
            - 'RetroArch SteamOS': 'emulators/steamos/retroarch.md'
            - 'RetroArch Windows': 'emulators/windows/retroarch.md'
        - Rosalie's Mupen GUI:
            - "Rosalie's Mupen GUI SteamOS": 'emulators/steamos/rmg.md'
        - RPCS3:
            - 'RPCS3 SteamOS': 'emulators/steamos/rpcs3.md'
            - 'RPCS3 Windows': 'emulators/windows/rpcs3.md'
        - Ryujinx:
            - 'Ryujinx SteamOS': 'emulators/steamos/ryujinx.md'
            - 'Ryujinx Windows': 'emulators/windows/ryujinx.md'
        - ScummVM:
            - 'ScummVM SteamOS': 'emulators/steamos/scummvm.md'
        - Vita3K:
            - 'Vita3K SteamOS': 'emulators/steamos/vita3k.md'
        - Xemu:
            - 'Xemu SteamOS': 'emulators/steamos/xemu.md'
        - Xenia:
            - 'Xenia SteamOS': 'emulators/steamos/xenia.md'
        - Yuzu:
            - 'Yuzu SteamOS': 'emulators/steamos/yuzu.md'
            - 'Yuzu Windows': 'emulators/windows/yuzu.md'
    - Other:
        - EmuDeck for SteamOS:
            - Community Creations: 'other/steamos/community-creations.md'
            - File Management: 'other/steamos/file-management.md'
            - Third Party Emulation: 'other/steamos/third-party-emulation.md'  
        - EmuDeck for Windows:
            - File Management: 'other/windows/file-management.md'
theme:
    name: material     
    custom_dir: overrides 
    features:
        - toc.integrate 
        - navigation.top
        - search.suggest
        - search.highlight
        - search.share
    plugins:
        - search
    markdown_extensions:
        - pymdownx.superfences:
            custom_fences:
                - name: mermaid
                  class: mermaid
                  format: !!python/name:pymdownx.superfences.fence_code_format
        - pymdownx.emoji:
            emoji_index: !!python/name:materialx.emoji.twemoji
            emoji_generator: !!python/name:materialx.emoji.to_svg
            options:
                custom_icons:
                    - overrides/.icons
        - def_list
        - sane_lists
        - attr_list
        - tables
        - pymdownx.keys
        - pymdownx.caret
        - md_in_html          
        - pymdownx.tasklist:
    custom_checkbox: true
    logo: assets/logo.png
    favicon: images/favicon.png
    font:
        text: Open Sans
        code: IBM Plex Mono
    palette:
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: 'blue'
        accent: 'light blue'
        toggle:
            icon: material/brightness-4
            name: Toogle light mode
      - media: "(prefers-color-scheme: light)"
        scheme: light
        primary: 'blue'
        accent: 'light blue'
        toggle:
            icon: material/brightness-7
            name: Toggle dark mode


extra:
  social:
    - icon: 'custom/logo'
      link: 'https://www.emudeck.com/'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/EmuDeck'
    - icon: 'fontawesome/brands/discord'
      link: 'https://discord.gg/b9F7GpXtFP'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/EmuDeck'
    - icon: 'fontawesome/brands/patreon'
      link: 'https://www.patreon.com/dragoonDorise'

